### ISSUE TITLE
Current Code is not Supporting Multiple Diversion Headers

### ISSUE THREAD

**Issue by abhijeet0202** [tropo/tropo-webapi-java#17]
I am facing a scenario where:
User [Say Z] Called User A, 
which later get diverted to User B and finally get diverted to Voice mail.
Now, Voicemail should drop a voice message to actual Called Party [That is User A] based on Diversion Header value.[ Please see RFC link]
https://tools.ietf.org/html/rfc5806

But,
Current Code Implement:
https://github.com/tropo/tropo-webapi-java/blob/master/src/main/java/com/voxeo/tropo/TropoSession.java [supports HashMap. private HashMap<String, String> headers;]
Which actually overwrite the first Diversion Header Value and save the last one

For Example we received below field:
"Diversion": "  <sip:UserA@cisco.com>;reason=no-answer [ Expected USer in Hashmap ]
"Diversion": "  <sip: UserB@cisco.com>;reason=busy
"Diversion": "  <sip: UserC@cisco.com>;reason=no-answer [Currently Present in Hashmap]

if we change current code from
private HashMap<String, String> headers;
to 
private MultivaluedMap<String, String> headers;
This will resolve this problems
Please provide your valuable  impact.

Thanks
\Abhijeet
Please let me know

**Comment by mpermar** [comment]
I think in general multiple headers with same name will not be supported as it is not clear either whether that is allowed in JSON or not (mixed opinions and interpretations over the diferent RFCs about it ). Therefore the libraries struggle to parse such scenario and certainly net.sf.json.JsonObject which is an old implementation of a json parser fails to do it. 

You might try to switch from net.sf.json.JsonObject to Gson and we are happy to take a pull request should it pass all the existing tests. I would imagine that a custom deserializer might do the trick. 

Another alternative is to ask the Tropo team to see if they can return headers in a more json-friendly way with an array of values for headers that share the same key. Then the pull request becomes much simpler as it is rather a matter of switching the map from <String,String> to <String,Object>
