### ISSUE TITLE
Not able to access public maven Repository of webApi, is URL changed, not able to ping also

### ISSUE THREAD

**Issue by abhijeet0202** [tropo/tropo-webapi-java#23]
<repositories>
    <repository>
      <id>tropo-public</id>
      <name>Uncle Tropos's Public Maven Repo</name>
      <url>http://maven.tropo.com:8081/nexus/content/groups/public</url>
    </repository>
  </repositories>

**Comment by mpermar** [comment]
Hi. abhijeet0202. Yes, we are having some issues with the public maven repository. While the team tries to fix it I'd recommend to local build the dependency.

**Comment by abhijeet0202** [comment]
Thanks, Please do let me know once it get fixed.

**Comment by mpermar** [comment]
Took a little bit but finally we have moved the java webapi build to Maven's central repository. That should sort you @abhijeet0202 .
