### ISSUE TITLE
Allow client to provide HttpClient

### ISSUE THREAD

**Issue by smithtj1** [tropo/tropo-webapi-java#27]
I'd like to be able to specify the connection and socket timeouts for the underlying HttpClient used by the Tropo.launchSession(...) methods. Currently they are defaulted to -1 (infinite).

Would it be possible to overload that method to take an HttpClient it can pass to the SessionLauncher that will be used for the connection?

For what its worth, I have [some changes of the like on my fork](https://github.com/tropo/tropo-webapi-java/compare/master...smithtj1:master), it could always be abstracted into a generic HttpSettings if you don't want com.voxeo.tropo.Tropo to have knowledge of HttpClient. Let me know if you'd be open to me creating a PR. 

Thanks!

**Comment by mpermar** [comment]
Hi @smithtj1 . Looks good. I am happy to merge it if you send the PR.

**Comment by mpermar** [comment]
Thanks @smithtj1 . Got that one merged and bumped the version on the Maven repo. It'll take a little bit to propagate.
