### ISSUE TITLE
why the version jump from 0.4 directly to 15.8?

### ISSUE THREAD

**Issue by imhazige** [tropo/tropo-webapi-java#46]
we are very curious why the version jump directly from 0.4 to 15.8, we are using the lib in a product, we hope there are nothing wrong in the new release.

**Comment by ralfschiffert** [comment]
There is very likely an alignment between the Tropo hosted version and the helper library version. 
See here http://changes.tropo.com/

**Comment by imhazige** [comment]
sounds good, thanks!
