### ISSUE TITLE
For event like Continue and timeout,  say  is mandatory

### ISSUE THREAD

**Issue by krishnadassc** [tropo/tropo-webapi-java#48]
Tropo tropo = new Tropo();
		tropo.on(Key.EVENT("continue"), Key.NEXT("/continue.json"),
				Key.SAY_OF_ON(new com.voxeo.tropo.actions.OnAction.Say("continue")));
Key.SAY_OF_ON should not be mandatory.

**Comment by pengxli** [comment]
say is required,refer to [https://www.tropo.com/docs/webapi/on](https://www.tropo.com/docs/webapi/on)

**Comment by pengxli** [comment]
The issue has been solved.
